/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "WaveDAC8_1.h"
#include "WaveDAC8_2.h"
#include "UART_1.h"
#include "PWM_1.h"
#include "Master_Clk.h"
#include "Opamp_1.h"
#include "Pin_Out_AMP_aliases.h"
#include "Pin_Out_AMP.h"
#include "Pin_I_AMP_aliases.h"
#include "Pin_I_AMP.h"
#include "Pin_DAC_1_aliases.h"
#include "Pin_DAC_1.h"
#include "Pin_DAC_2_aliases.h"
#include "Pin_DAC_2.h"
#include "Pin_NI_AMP_aliases.h"
#include "Pin_NI_AMP.h"
#include "PWM_2.h"
#include "WaveDAC8_1_Wave1_DMA_dma.h"
#include "WaveDAC8_1_Wave2_DMA_dma.h"
#include "WaveDAC8_1_VDAC8.h"
#include "WaveDAC8_2_Wave1_DMA_dma.h"
#include "WaveDAC8_2_Wave2_DMA_dma.h"
#include "WaveDAC8_2_VDAC8.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

